# Generated by Django 4.2.9 on 2024-04-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp500', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='E',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ESG',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='G',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='S',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
